services:
  elasticsearch-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch-node-1
    environment:
      - cluster.name=es-cluster
      - node.name=node-1
      - discovery.seed_hosts=elasticsearch-node-1,elasticsearch-node-2
      - cluster.initial_master_nodes=node-1,node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
     # - net.ipv4.ip_forward=1
    ports:
      - "9201:9200"
    volumes:
      - /elastic01/data1:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 6g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
 
  elasticsearch-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch-node-2
    environment:
      - cluster.name=es-cluster
      - node.name=node-2
      - discovery.seed_hosts=elasticsearch-node-1,elasticsearch-node-2
      - cluster.initial_master_nodes=node-1,node-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      #- net.ipv4.ip_forward=1
    ports:
      - "9202:9200"
    volumes:
      - /elastic01/data2:/usr/share/elasticsearch/data
    networks:
      - elastic_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 6g
   apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.3
    container_name: apm-server
    environment:
      -NAME= apm-server
      -USER =apm-server
      -"NETWORK_HOST=0.0.0.0"
      - SERVER_HOST=0.0.0.0
      - output_elasticsearch_hosts=["http://172.25.179.241:9201"]
    ports:
      - "8200:8200"
    networks:
      - kibana_network
    deploy:
      resources:
        limits:
          memory: 4g
networks:
  elastic_network:
    driver: bridge
